### ISSUE TITLE
Custom cloth not working

### ISSUE THREAD

**Issue by reshadhstu** [lastdefiance20/TryYours-Virtual-Try-On#1]
When I upload custom cloth, it's not working. Only showing the predefined cloth.

**Comment by lastdefiance20** [comment]
Hi, I checked my colab code and it was working well (uploading & processing).

I don't know what part you are troubled with.

In the google colab code, under "3. Upload Colth Images", you need to select the file after running the code. Then, Custom Cloth will save as cloth_web.jpg and saved in /TryYours-Virtual-Try-On/static/cloth_web.jpg and will show "5. Check Images"

If your problem is not what I described, please share more information about your problem or the custom cloth image you are trying to use.

thanks for your interest in our project.

![image](https://user-images.githubusercontent.com/65525866/223323054-2613d9c0-c934-4e98-beff-a8829061ba96.png)

![image](https://user-images.githubusercontent.com/65525866/223323083-92dfe10d-1c88-4059-98a9-cf5e73375b11.png)

**Comment by reshadhstu** [comment]
I've managed to work. Need to resize the cloth image. The large image size not working. Thank you.

**Comment by lastdefiance20** [comment]
Got it. I should fix the code to work on the large images. Thank you for your issue.
