### ISSUE TITLE
Not able to generate data.json

### ISSUE THREAD

**Issue by nazapip** [lastdefiance20/TryYours-Virtual-Try-On#10]
Hi,
@lastdefiance20  I am not able to generate data.json file. Instead of getting output saved to data.json, i get output saved to output.pkl and getting the distorted image.
![Screenshot 2023-06-26 175910](https://github.com/lastdefiance20/TryYours-Virtual-Try-On/assets/137103045/955f4c3f-519c-481d-b7e1-deb8a30647e0)

**Comment by lastdefiance20** [comment]
Hi @nazapip, what does it mean "not able to generate data.json file"? can you give me more information about your error?
I run the google colab code and run the code locally, there was no error.
And about use/generate of JSON file, we use a JSON file generated by "posenet.py" to get openpose coordinates. I'm not sure what error you faced, but I think an error occurs on this part.

**Comment by nazapip** [comment]
_Thanks,
On google colab code is running perfectly fine, the issue is while running it locally.

This is all what i am getting on the local machine:_

[32m[06/26 20:11:52 apply_net]: [0mProcessing origin.jpg
[32m[06/26 20:11:52 apply_net]: [0m**Output saved to output.pkl**

File "/TryYours-Virtual-Try-On/get_densepose.py", line 27, in <module>
    with open('./data.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data.json'

The below image is the output of the colab file(which is working totally fine) where i get 'output saved at data.json' unlike the above error
![image](https://github.com/lastdefiance20/TryYours-Virtual-Try-On/assets/137103045/19a78c38-b16f-44eb-81fd-62ee82a1ec0c)

**Comment by lastdefiance20** [comment]
@nazapip Ok, I know what is the issue. you should use the detectron2 library folder inside my project.

https://github.com/lastdefiance20/TryYours-Virtual-Try-On/blob/29ef6e2b1e730ac131623ceddc4acf4f5699b3bd/main.py#L59C1-L65C33

In this code, we call 'apply_net.py' in this 'main.py' code to generate an output densepose JSON file.

https://github.com/lastdefiance20/TryYours-Virtual-Try-On/blob/29ef6e2b1e730ac131623ceddc4acf4f5699b3bd/detectron2/projects/DensePose/apply_net.py#L186C1-L198C50

And I change the code inside of 'apply_net.py' like this to save it as a JSON file instead of pkl file. so you should use / or install the detectron2 library as a colab instruction follows to generate JSON other than the pkl file.

**Comment by nazapip** [comment]
Thanks Brother!!..
Code is working perfect now

Can you please elaborate a bit that what was the need to do this specific changes? in apply.net code
